# status file name format
# <pid>_<name>_status_file.yaml

jobs:
  4fb40dd8-68c0-485c-a738-965fb5d517ab:
    executor: 'python'
    file: 'example_services/example_service_0.py'
    arguments:
      '--name': 'tenants_name'

    command: null

    dotenv: true
    env_files: []
    environment: {}

services:
  tenants:
    init_config:
      executor: 'python'
      file: 'example_services/example_service_0.py'
      arguments:
        '--name': 'tenants_name'

      command: null

      dotenv: true
      env_files: []
      environment: {}

      name: 'test_process'
      service: true
    service_data:
      nginx_config: ''
      port: 123456789
    system_data:
#      error_code: None
#      pid: 214826
      state: STARTED
